### ISSUE TITLE
Docker Compose with CosmosDB

### ISSUE THREAD

**Issue by VladislavAntonyuk** [microsoft/fhir-server#2140]
You provided an example of how to use docker with SQLServer. 
Could you provide an example of how to use it with CosmosDB
Thank you.

AB#101796

**Comment by brendankowitz** [comment]
Thanks for the feedback. Just clarifying you're referring to this page? https://github.com/microsoft/fhir-server/tree/main/samples/docker

We don't have this example now, but in the meantime the DevContainer setup does use Cosmos which you could refer to:
https://github.com/microsoft/fhir-server/blob/main/.devcontainer/docker-compose.yml

**Comment by VladislavAntonyuk** [comment]
I tried to change your file to something like this:
```
version: "3"
services:
  fhir-api:
    build: 
      context: ./../../
      dockerfile: ./build/docker/Dockerfile
      args:
        FHIR_VERSION: R4
    restart: on-failure
    environment:
      FHIRServer__Security__Enabled: "false"
     DataStore: "CosmosDb"
    ports:     
      - "8080:8080"
    depends_on:
      - cosmos

  cosmos:
    image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator"
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 10
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    ports: 
      - 8081:8081
      - 8900:8900
      - 8901:8901
      - 8979:8979
      - 10250:10250
      - 10251:10251
      - 10252:10252
      - 10253:10253
      - 10254:10254
      - 10255:10255
      - 10256:10256
      - 10350:10350
```
But I receive the error:
```
 Microsoft.Health.Fhir.CosmosDb.Features.Storage.CosmosContainerProvider[0]
Couldn't create a ContainerScope because EnsureInitialized failed.
System.Net.Http.HttpRequestException: Address not available (localhost:8081)
---> System.Net.Sockets.SocketException (99): Address not available
```
